# Generated by Django 5.2.7 on 2025-10-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networktask',
            name='task_type',
            field=models.CharField(choices=[('vlan_create', 'Create VLAN'), ('vlan_delete', 'Delete VLAN'), ('interface_config', 'Configure Interface'), ('routing_static', 'Static Route'), ('routing_ospf', 'OSPF Configuration'), ('vrf_create', 'Create VRF'), ('vrf_delete', 'Delete VRF'), ('vrf_interface', 'Assign VRF to Interface'), ('bgp_neighbor', 'Configure BGP Neighbor'), ('bgp_network', 'Advertise BGP Network'), ('bgp_vrf', 'Configure BGP for VRF'), ('show_version', 'Show Version'), ('show_interfaces', 'Show Interfaces'), ('show_vlan', 'Show VLANs'), ('show_routes', 'Show Routes'), ('show_vrf', 'Show VRFs'), ('show_bgp', 'Show BGP Summary'), ('backup_config', 'Backup Configuration')], max_length=20),
        ),
    ]
